### ISSUE TITLE
Loads forever on server with custom resource pack

### ISSUE THREAD

**Issue by Tiebe** [QuantumFusionMC/DashLoader-Core#2]
On servers it will load forever with the message `Mapping particles` on the screen. It gives the following error in console: 

```
java.lang.NullPointerException: Cannot invoke "java.util.Map.size()" because "particles" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17+build.10)
	at dev.quantumfusion.dashloader.def.corehook.holder.DashParticleData.<init>(DashParticleData.java:37)
	at dev.quantumfusion.dashloader.def.corehook.MappingData.map(MappingData.java:82)
	at dev.quantumfusion.dashloader.def.DashLoader.saveDashCache(DashLoader.java:186)
	at java.lang.Thread.run(Thread.java:833)
```

**Comment by alphaqu** [comment]
Please report the issue on https://github.com/QuantumFusionMC/DashLoader-Definitions instead of Core.

**Comment by leocth** [comment]
yknow, you can transfer issues on GH
